[package]
name = "nugget-cli"
edition.workspace = true
version.workspace = true

[[bin]]
name = "nugget"
path = "src/main.rs"

[dependencies]
nugget-store = { path = "../nugget-store" }
clap = { workspace = true }

[dev-dependencies]
tempfile = "3"
