[package]
name = "nugget-store"
version = "0.1.0"
edition = "2021"

[dependencies]
nugget-core = { path = "../nugget-core" }
serde = { workspace = true }
serde_yaml = { workspace = true }
anyhow = { workspace = true }
walkdir = "2"

[dev-dependencies]
tempfile = "3"
